version: '3.9'

services:
  rag_server:
    build:
      context: ./RAG
      dockerfile: Dockerfile.rag
    ports:
      - "8000:8000"
    volumes:
      - ./RAG:/app

  rasa_server:
    build:
      context: ./RASA
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    volumes:
      - ./RASA:/app
    depends_on:
      - rasa_actions
    command: rasa run --enable-api --cors "*" --debug

  rasa_actions:
    build:
      context: ./RASA
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./RASA/actions:/app/actions


  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "8080:80"