base_model: meta-llama/Meta-Llama-3-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

trust_remote_code: true
push_to_hub: false

load_in_4bit: true  # or false if you want full precision
strict: false

datasets:
  - path: ../data/rag_dataset.jsonl
    type: chat  # use 'chat' if your data is formatted as multi-turn dialogs

val_set_size: 0.05
output_dir: ../outputs/llama3-finetuned

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

lora:
  r: 16
  alpha: 32
  dropout: 0.05
  target_modules:
    - q_proj
    - v_proj
lora_bias: none
lora_task_type: CAUSAL_LM

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5

save_every_n_steps: 100
logging_steps: 10
