FROM python:3.10-slim

# Install system dependencies include tkinter
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-tk \
    build-essential \
    curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app
COPY requirements.txt .

# Install everything globally (NO venv)
RUN pip install --upgrade pip && pip install --no-cache-dir rasa==3.6.21 -r requirements.txt

RUN rasa train

# Run Rasa shell
CMD ["rasa", "shell"]
